### ISSUE TITLE
Obsługa zdarzeń wejścia - InputListener

### ISSUE THREAD

**Issue by lethiandev** [konrad92/slashnsmash#1]
Implementacja modułu do rejestracji i obsługi zdarzeń urządzeń wejścia, tj. klawiatura, gamepady, touch gestures.

**Comment by konrad92** [comment]
@PrzemekX

**Comment by lethiandev** [comment]
@PrzemekX Zaprezentuj nam interfejs, jaki będzie mieć moduł.

**Comment by lethiandev** [comment]
TL;DC
