### ISSUE TITLE
Zwierzątko bug

### ISSUE THREAD

**Issue by qiku1337** [konrad92/slashnsmash#4]
Gdy się nie poruszysz, zwierzątka nie podążają za postacią, tylko idą sobie hen daleko w dal.
Nie obracają się w kierunku tam gdzie postać patrzy.

**Comment by szapko** [comment]
Rude koty, to niby nasi wrogowie, a biały kot, daje nam powera do zabijania :) dlatego jak biały kot przebiegł za wysoko to go nie zebraliśmy. Rude koty na razie są po prostu nacelowane na nas, od chyba 100 punktów/pikseli odległości od nas dopiero mają ruszać na nas i atakować.
Problem w tym, że jak zrobiłem opóźnienie dla komunikatów w konsoli, żeby za szybko nie przemijały, gra się ścina fps spadają i nie wiem jak to poprawić na razie.

**Comment by lethiandev** [comment]
Później dorobię odskakiwanie gracza po ciosie wroga, keep calm and pull commits
